### ISSUE TITLE
Update the Envoy fuzz target implementation to use the new cc_fuzz_test components in this repo.

### ISSUE THREAD

**Issue by stefanbucur** [bazelbuild/rules_fuzzing#21]

**Comment by asraa** [comment]
The `envoy_cc_fuzz_target` macro is defined here https://github.com/envoyproxy/envoy/blob/606ccbdc2ab956d0f8190e30990d3aa6643d7547/bazel/envoy_test.bzl#L73.

It creates four things:
1. a `pkg_tar` to compress the corpus. We build this for OSS-Fuzz.
2. a test library for the fuzz test
3. an engine-less binary target that just depends on the test library. We build this for OSS-Fuzz, which links in other engines.
4. the actual test targets: (1) linked with libfuzzer when run with `--config asan-fuzzer`, and (2) linked with gtest otherwise

We should be able to swap out 4.1 (libfuzzer test target) pretty soon. It would be the rule imported from here, with the test library dependency, and the launcher that would take the corpus from the macro argument. We currently don't have a launcher script equivalent, any options we pass have to be manually added like the corpus or a dictionary, so that would be a big win.
We use this target for coverage builds, there may be some complexity here, but we can chat and go over it, it may be too hard to type. The launcher script would simplify things for us greatly.

Another big win for a future iteration would be packaging the engine-less target together with the zipped corpus for a single OSS-Fuzz target to build. We currently build the targets and corpora separately https://github.com/google/oss-fuzz/blob/f743ea9d3b78879c858c21cd405d3708249756de/projects/envoy/build.sh#L86

**Comment by asraa** [comment]
1. Replace libfuzzer linked target from 4.1
2. Implement zip target in bazel-rules-fuzzing and replace (1) and (3)
3. Figure out how to deal with 4.2 (gtest linked target)

**Comment by stefanbucur** [comment]
This is now fixed in envoyproxy/envoy#14834.
